### ISSUE TITLE
Add math functionality to attribute values

### ISSUE THREAD

**Issue by trevorvanhoof** [peerke88/cmdWrapper#1]
Whenever getting a multi-dimensional attribute we may want to add math functionality to it,
I.e. transform.worldMatrix[0]() can return an MMatrix, transform.translate() can return an MVector.

Therefore the plan is simply checking the returned value and if it is a multi-dimensional float we cast it to the right class.
The goal of the class is to work 100% identical to the returned value (i.e. a tuple of 3 floats should be indistinguishable from a Vec3 instance when used in code), but add MVector / MPoint / MQuaternion / MMatrix features on top where applicable.

Notes:
We considered is another approach to this, being transform.tx() returns a float, and python's math module has
functions to manipulate that float. In this fashion we could create functions like "def normalize(vec):", but overriding max() and abs() to also support MVector seems invasive in builtin Python features so we should opt not to.

We considered using cmds.getAttr(type=True) to see if something is a double3, but cmds.xform does not work like that for example.

We considered using explicit functions, especially for MQuaternion, like transform.getR(), but some node attributes simply return 4 floats and we want to use quaternion funcionality with them, so again return-value-type is more important than any other contextual information we can assume from node name / type and attribute name / type.

**Comment by peerke88** [comment]
has been merged into main
